#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
// TODO: Test if this function is properly adapted to be called from C...
void RotateVector(int32_t norme, int32_t alpha, int32_t beta, int32_t gamma);

// =============================================================================
#ifdef __cplusplus
}
#endif
