#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
uint32_t Sqr(uint32_t x);
uint32_t QSqr(uint32_t xLow, uint32_t xHigh);

// =============================================================================
#ifdef __cplusplus
}
#endif
