#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
extern int32_t CalcGraphMsk(int32_t numbrick, void *bankbrick, void *ptmask);

// =============================================================================
#ifdef __cplusplus
}
#endif
