#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
int32_t CopyMask(int32_t nummask, int32_t x, int32_t y, void *bankmask, void *src);

// =============================================================================
#ifdef __cplusplus
}
#endif
