#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// --- Initialization ----------------------------------------------------------
bool InitGraphics(uint32_t resX, uint32_t resY);
void EndGraphics();

// =============================================================================
#ifdef __cplusplus
}
#endif
