#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
void Plot(int32_t x0, int32_t y0, int32_t col);
int32_t GetPlot(int32_t x0, int32_t y0);

// =============================================================================
#ifdef __cplusplus
}
#endif
