#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
extern void SaveBlock(void *screen, void *buffer, int32_t x0, int32_t y0, int32_t x1,
                      int32_t y1);

// =============================================================================
#ifdef __cplusplus
}
#endif
