#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
extern void ScaleSpriteTransp(int32_t num, int32_t x, int32_t y, int32_t factorx, int32_t factory,
                              void *ptrbank, void *ptr_transp);

// =============================================================================
#ifdef __cplusplus
}
#endif
