#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
void ScaleSprite(int32_t num, int32_t x, int32_t y, int32_t factorx, int32_t factory,
                        void *ptrbank);

// =============================================================================
#ifdef __cplusplus
}
#endif
