#pragma once

#include <SYSTEM/ADELINE_TYPES.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
extern int32_t ScreenXMin;
extern int32_t ScreenYMin;
extern int32_t ScreenXMax;
extern int32_t ScreenYMax;

// =============================================================================
#ifdef __cplusplus
}
#endif
