//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

#define	MAX_BUGGYS	2

//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
/*──────────────────────────────────────────────────────────────────────────*/
typedef struct {

	int32_t	Angle ;
	int32_t	X ;
	int32_t	Y ;
	int32_t	Z ;

		}	S_ONE_WHEEL ;

typedef struct {

	int32_t	X ;
	int32_t	Y ;
	int32_t	Z ;
	int32_t	Cube ;
	int32_t	Beta	;
	int32_t	Alpha	;
	int32_t     Gamma	;

	S_ONE_WHEEL	Wheel[4] ;

	int32_t		BetaWheel ;

	int32_t		SpeedInc ;
	int32_t		SpeedRot ;

	int32_t		Speed ;

//	int32_t		YSpeed ;
//	int32_t		LastYs ;
//	int32_t		LastSpeedLevel ;

	int32_t		LastTimer ;

		} S_BUGGY ;

//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

#define	BUGGY_PRESENT		0x80
#define	NUM_BUGGY		((uint8_t)(NumBuggy&~(BUGGY_PRESENT)))
#define	IsBuggyPresent()        (NumBuggy&BUGGY_PRESENT)

extern	S_BUGGY	ListBuggy[MAX_BUGGYS] ;
extern	uint8_t	NumBuggy	;

//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

//■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
extern	void	InitBuggy( uint8_t numobj, uint32_t flaginit ) ;

//■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
extern	void	ResetBuggy( void ) ;

//■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
extern	void	TakeBuggy( void )	;

//■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
extern	void	LeaveBuggy( uint8_t newcomportement ) ;

//■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
extern	void	DoAnimBuggy( T_OBJET *ptrobj ) ;

//■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
extern	void	MoveBuggy( T_OBJET *ptrobj ) ;

//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
