#ifndef	CRITICAL_H
#define	CRITICAL_H

#define	CRITICAL_ERROR_COUNT_FAILURE	50

extern	int32_t	CriticalErrorCount ;

//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
extern	int __far CriticalErrorHandler(	unsigned int deverr,
					unsigned int errcode,
					unsigned int __far *devhdr ) ;

//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
#define	InstallCriticalErrorHandler()	_harderr( CriticalErrorHandler )

#endif	// CRITICAL_H
