#ifndef	GERETRAK_H
#define	GERETRAK_H

/*--------------------------------------------------------------------------*/
extern int16_t  SearchOffsetTrack( T_OBJET *ptrobj, uint8_t label ) ;
/*--------------------------------------------------------------------------*/
extern void Track_SetLabel( T_OBJET *ptrobj ) ;
/*--------------------------------------------------------------------------*/
extern void DoTrack(uint8_t numobj);
/*--------------------------------------------------------------------------*/

#endif	// GERETRAK_H
