/*
				POF.H

			   Gestion des pofs

*/

#ifndef	POF_H
#define	POF_H

//----------------------------------------------------------------------------------

#ifdef	LBA_EDITOR
#define	PATH_POF	"f:\\projet\\lba2\\datas\\pof\\"
#endif

//----------------------------------------------------------------------------------
extern int32_t PofDisplay3DExt( int32_t x, int32_t y, int32_t z, int32_t num_pof, int32_t scale, int32_t rotation ) ;
//----------------------------------------------------------------------------------

#endif	/* POF_H */
