#ifndef	VALIDPOS_H
#define	VALIDPOS_H

#define	SIZE_BUFFER_VALIDE_POS	50000L	// a reajuster

extern	int32_t	ValideCube		;

extern	int32_t	ValidePos		;
extern	int32_t	LastValidePos		;

extern	T_OBJET	ValideHero ;
extern	uint32_t	SizeOfBufferValidePos	;
extern	uint8_t	*BufferValidePos	;

//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
extern	void	SaveValidePos( void ) ;
//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
extern	void	RestartValidePos( void ) ;
//▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

#endif	// VALIDPOS_H
