#include <SVGA/SCREENXY.H>

// -----------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif

// -----------------------------------------------------------------------------
int32_t ScreenXMin = 0;
int32_t ScreenYMin = 0;
int32_t ScreenXMax = 0;
int32_t ScreenYMax = 0;

// =============================================================================
#ifdef __cplusplus
}
#endif
